import { create } from 'zustand'

export const useDataStore = create((set) => ({
  categori: ["economy", "politics", "technology", "society", "world", "culture"],
  currentCategori: "economy",
  contents: [
    [
      { index: 0, title: "Ecnonomy title1", article: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Non, quo nesciunt aliquid nulla eveniet cupiditate odit nemo dolor nobis vel dicta, aliquam suscipit id assumenda eius consectetur blanditiis Lorem ipsum dolor sit amet consectetur adipisicing elit. Non, quo nesciunt aliquid nulla eveniet cupiditate odit nemo dolor nobis vel dicta, aliquam suscipit id assumenda eius consectetur blanditiis", img: "img", time: 'time' },
      { index: 1, title: "Ecnonomy title2", article: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Non, quo nesciunt aliquid nulla eveniet cupiditate odit nemo dolor nobis vel dicta, aliquam suscipit id assumenda eius consectetur blanditiis Lorem ipsum dolor sit amet consectetur adipisicing elit. Non, quo nesciunt aliquid nulla eveniet cupiditate odit nemo dolor nobis vel dicta, aliquam suscipit id assumenda eius consectetur blanditiis", img: "img", time: 'time' },
      { index: 2, title: "Ecnonomy title3", article: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Non, quo nesciunt aliquid nulla eveniet cupiditate odit nemo dolor nobis vel dicta, aliquam suscipit id assumenda eius consectetur blanditiis Lorem ipsum dolor sit amet consectetur adipisicing elit. Non, quo nesciunt aliquid nulla eveniet cupiditate odit nemo dolor nobis vel dicta, aliquam suscipit id assumenda eius consectetur blanditiis", img: "img", time: 'time' },
      { index: 3, title: "Ecnonomy title4", article: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Non, quo nesciunt aliquid nulla eveniet cupiditate odit nemo dolor nobis vel dicta, aliquam suscipit id assumenda eius consectetur blanditiis Lorem ipsum dolor sit amet consectetur adipisicing elit. Non, quo nesciunt aliquid nulla eveniet cupiditate odit nemo dolor nobis vel dicta, aliquam suscipit id assumenda eius consectetur blanditiis", img: "img", time: 'time' },
      { index: 4, title: "Ecnonomy title5", article: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Non, quo nesciunt aliquid nulla eveniet cupiditate odit nemo dolor nobis vel dicta, aliquam suscipit id assumenda eius consectetur blanditiis Lorem ipsum dolor sit amet consectetur adipisicing elit. Non, quo nesciunt aliquid nulla eveniet cupiditate odit nemo dolor nobis vel dicta, aliquam suscipit id assumenda eius consectetur blanditiis", img: "img", time: 'time' }
    ],
    [
      { index: 0, title: "politics title1", article: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Non, quo nesciunt aliquid nulla eveniet cupiditate odit nemo dolor nobis vel dicta, aliquam suscipit id assumenda eius consectetur blanditiis Lorem ipsum dolor sit amet consectetur adipisicing elit. Non, quo nesciunt aliquid nulla eveniet cupiditate odit nemo dolor nobis vel dicta, aliquam suscipit id assumenda eius consectetur blanditiis", img: "img", time: 'time' },
      { index: 1, title: "politics title2", article: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Non, quo nesciunt aliquid nulla eveniet cupiditate odit nemo dolor nobis vel dicta, aliquam suscipit id assumenda eius consectetur blanditiis Lorem ipsum dolor sit amet consectetur adipisicing elit. Non, quo nesciunt aliquid nulla eveniet cupiditate odit nemo dolor nobis vel dicta, aliquam suscipit id assumenda eius consectetur blanditiis", img: "img", time: 'time' },
      { index: 2, title: "politics title3", article: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Non, quo nesciunt aliquid nulla eveniet cupiditate odit nemo dolor nobis vel dicta, aliquam suscipit id assumenda eius consectetur blanditiis Lorem ipsum dolor sit amet consectetur adipisicing elit. Non, quo nesciunt aliquid nulla eveniet cupiditate odit nemo dolor nobis vel dicta, aliquam suscipit id assumenda eius consectetur blanditiis", img: "img", time: 'time' },
      { index: 3, title: "politics title4", article: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Non, quo nesciunt aliquid nulla eveniet cupiditate odit nemo dolor nobis vel dicta, aliquam suscipit id assumenda eius consectetur blanditiis Lorem ipsum dolor sit amet consectetur adipisicing elit. Non, quo nesciunt aliquid nulla eveniet cupiditate odit nemo dolor nobis vel dicta, aliquam suscipit id assumenda eius consectetur blanditiis", img: "img", time: 'time' },
      { index: 4, title: "politics title5", article: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Non, quo nesciunt aliquid nulla eveniet cupiditate odit nemo dolor nobis vel dicta, aliquam suscipit id assumenda eius consectetur blanditiis Lorem ipsum dolor sit amet consectetur adipisicing elit. Non, quo nesciunt aliquid nulla eveniet cupiditate odit nemo dolor nobis vel dicta, aliquam suscipit id assumenda eius consectetur blanditiis", img: "img", time: 'time' }
    ],
    [
      { index: 0, title: "technology title1", article: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Non, quo nesciunt aliquid nulla eveniet cupiditate odit nemo dolor nobis vel dicta, aliquam suscipit id assumenda eius consectetur blanditiis Lorem ipsum dolor sit amet consectetur adipisicing elit. Non, quo nesciunt aliquid nulla eveniet cupiditate odit nemo dolor nobis vel dicta, aliquam suscipit id assumenda eius consectetur blanditiis", img: "img", time: 'time' },
      { index: 1, title: "technology title2", article: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Non, quo nesciunt aliquid nulla eveniet cupiditate odit nemo dolor nobis vel dicta, aliquam suscipit id assumenda eius consectetur blanditiis Lorem ipsum dolor sit amet consectetur adipisicing elit. Non, quo nesciunt aliquid nulla eveniet cupiditate odit nemo dolor nobis vel dicta, aliquam suscipit id assumenda eius consectetur blanditiis", img: "img", time: 'time' },
      { index: 2, title: "technology title3", article: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Non, quo nesciunt aliquid nulla eveniet cupiditate odit nemo dolor nobis vel dicta, aliquam suscipit id assumenda eius consectetur blanditiis Lorem ipsum dolor sit amet consectetur adipisicing elit. Non, quo nesciunt aliquid nulla eveniet cupiditate odit nemo dolor nobis vel dicta, aliquam suscipit id assumenda eius consectetur blanditiis", img: "img", time: 'time' },
      { index: 3, title: "technology title4", article: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Non, quo nesciunt aliquid nulla eveniet cupiditate odit nemo dolor nobis vel dicta, aliquam suscipit id assumenda eius consectetur blanditiis Lorem ipsum dolor sit amet consectetur adipisicing elit. Non, quo nesciunt aliquid nulla eveniet cupiditate odit nemo dolor nobis vel dicta, aliquam suscipit id assumenda eius consectetur blanditiis", img: "img", time: 'time' },
      { index: 4, title: "technology title5", article: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Non, quo nesciunt aliquid nulla eveniet cupiditate odit nemo dolor nobis vel dicta, aliquam suscipit id assumenda eius consectetur blanditiis Lorem ipsum dolor sit amet consectetur adipisicing elit. Non, quo nesciunt aliquid nulla eveniet cupiditate odit nemo dolor nobis vel dicta, aliquam suscipit id assumenda eius consectetur blanditiis", img: "img", time: 'time' }
    ],
    [
      { index: 0, title: "society title1", article: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Non, quo nesciunt aliquid nulla eveniet cupiditate odit nemo dolor nobis vel dicta, aliquam suscipit id assumenda eius consectetur blanditiis Lorem ipsum dolor sit amet consectetur adipisicing elit. Non, quo nesciunt aliquid nulla eveniet cupiditate odit nemo dolor nobis vel dicta, aliquam suscipit id assumenda eius consectetur blanditiis", img: "img", time: 'time' },
      { index: 1, title: "society title2", article: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Non, quo nesciunt aliquid nulla eveniet cupiditate odit nemo dolor nobis vel dicta, aliquam suscipit id assumenda eius consectetur blanditiis Lorem ipsum dolor sit amet consectetur adipisicing elit. Non, quo nesciunt aliquid nulla eveniet cupiditate odit nemo dolor nobis vel dicta, aliquam suscipit id assumenda eius consectetur blanditiis", img: "img", time: 'time' },
      { index: 2, title: "society title3", article: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Non, quo nesciunt aliquid nulla eveniet cupiditate odit nemo dolor nobis vel dicta, aliquam suscipit id assumenda eius consectetur blanditiis Lorem ipsum dolor sit amet consectetur adipisicing elit. Non, quo nesciunt aliquid nulla eveniet cupiditate odit nemo dolor nobis vel dicta, aliquam suscipit id assumenda eius consectetur blanditiis", img: "img", time: 'time' },
      { index: 3, title: "society title4", article: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Non, quo nesciunt aliquid nulla eveniet cupiditate odit nemo dolor nobis vel dicta, aliquam suscipit id assumenda eius consectetur blanditiis Lorem ipsum dolor sit amet consectetur adipisicing elit. Non, quo nesciunt aliquid nulla eveniet cupiditate odit nemo dolor nobis vel dicta, aliquam suscipit id assumenda eius consectetur blanditiis", img: "img", time: 'time' },
      { index: 4, title: "society title5", article: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Non, quo nesciunt aliquid nulla eveniet cupiditate odit nemo dolor nobis vel dicta, aliquam suscipit id assumenda eius consectetur blanditiis Lorem ipsum dolor sit amet consectetur adipisicing elit. Non, quo nesciunt aliquid nulla eveniet cupiditate odit nemo dolor nobis vel dicta, aliquam suscipit id assumenda eius consectetur blanditiis", img: "img", time: 'time' }
    ],
    [
      { index: 0, title: "world title1", article: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Non, quo nesciunt aliquid nulla eveniet cupiditate odit nemo dolor nobis vel dicta, aliquam suscipit id assumenda eius consectetur blanditiis Lorem ipsum dolor sit amet consectetur adipisicing elit. Non, quo nesciunt aliquid nulla eveniet cupiditate odit nemo dolor nobis vel dicta, aliquam suscipit id assumenda eius consectetur blanditiis", img: "img", time: 'time' },
      { index: 1, title: "world title2", article: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Non, quo nesciunt aliquid nulla eveniet cupiditate odit nemo dolor nobis vel dicta, aliquam suscipit id assumenda eius consectetur blanditiis Lorem ipsum dolor sit amet consectetur adipisicing elit. Non, quo nesciunt aliquid nulla eveniet cupiditate odit nemo dolor nobis vel dicta, aliquam suscipit id assumenda eius consectetur blanditiis", img: "img", time: 'time' },
      { index: 2, title: "world title3", article: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Non, quo nesciunt aliquid nulla eveniet cupiditate odit nemo dolor nobis vel dicta, aliquam suscipit id assumenda eius consectetur blanditiis Lorem ipsum dolor sit amet consectetur adipisicing elit. Non, quo nesciunt aliquid nulla eveniet cupiditate odit nemo dolor nobis vel dicta, aliquam suscipit id assumenda eius consectetur blanditiis", img: "img", time: 'time' },
      { index: 3, title: "world title4", article: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Non, quo nesciunt aliquid nulla eveniet cupiditate odit nemo dolor nobis vel dicta, aliquam suscipit id assumenda eius consectetur blanditiis Lorem ipsum dolor sit amet consectetur adipisicing elit. Non, quo nesciunt aliquid nulla eveniet cupiditate odit nemo dolor nobis vel dicta, aliquam suscipit id assumenda eius consectetur blanditiis", img: "img", time: 'time' },
      { index: 4, title: "world title5", article: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Non, quo nesciunt aliquid nulla eveniet cupiditate odit nemo dolor nobis vel dicta, aliquam suscipit id assumenda eius consectetur blanditiis Lorem ipsum dolor sit amet consectetur adipisicing elit. Non, quo nesciunt aliquid nulla eveniet cupiditate odit nemo dolor nobis vel dicta, aliquam suscipit id assumenda eius consectetur blanditiis", img: "img", time: 'time' }
    ],
    [
      { index: 0, title: "culture title1", article: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Non, quo nesciunt aliquid nulla eveniet cupiditate odit nemo dolor nobis vel dicta, aliquam suscipit id assumenda eius consectetur blanditiis Lorem ipsum dolor sit amet consectetur adipisicing elit. Non, quo nesciunt aliquid nulla eveniet cupiditate odit nemo dolor nobis vel dicta, aliquam suscipit id assumenda eius consectetur blanditiis", img: "img", time: 'time' },
      { index: 1, title: "culture title2", article: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Non, quo nesciunt aliquid nulla eveniet cupiditate odit nemo dolor nobis vel dicta, aliquam suscipit id assumenda eius consectetur blanditiis Lorem ipsum dolor sit amet consectetur adipisicing elit. Non, quo nesciunt aliquid nulla eveniet cupiditate odit nemo dolor nobis vel dicta, aliquam suscipit id assumenda eius consectetur blanditiis", img: "img", time: 'time' },
      { index: 2, title: "culture title3", article: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Non, quo nesciunt aliquid nulla eveniet cupiditate odit nemo dolor nobis vel dicta, aliquam suscipit id assumenda eius consectetur blanditiis Lorem ipsum dolor sit amet consectetur adipisicing elit. Non, quo nesciunt aliquid nulla eveniet cupiditate odit nemo dolor nobis vel dicta, aliquam suscipit id assumenda eius consectetur blanditiis", img: "img", time: 'time' },
      { index: 3, title: "culture title4", article: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Non, quo nesciunt aliquid nulla eveniet cupiditate odit nemo dolor nobis vel dicta, aliquam suscipit id assumenda eius consectetur blanditiis Lorem ipsum dolor sit amet consectetur adipisicing elit. Non, quo nesciunt aliquid nulla eveniet cupiditate odit nemo dolor nobis vel dicta, aliquam suscipit id assumenda eius consectetur blanditiis", img: "img", time: 'time' },
      { index: 4, title: "culture title5", article: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Non, quo nesciunt aliquid nulla eveniet cupiditate odit nemo dolor nobis vel dicta, aliquam suscipit id assumenda eius consectetur blanditiis Lorem ipsum dolor sit amet consectetur adipisicing elit. Non, quo nesciunt aliquid nulla eveniet cupiditate odit nemo dolor nobis vel dicta, aliquam suscipit id assumenda eius consectetur blanditiis", img: "img", time: 'time' }
    ]
  ],

  topics: ["topic1", "topic2", "topic3", "topic4", "topic5"],
  getContentsLength: () => {
    return
  }
}))
